<!DOCTYPE html>
<html>
<head>
    <title>SmartStock Sales Report</title>

    <style>

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            color: #111827;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 10px;
        }

        .summary {
            margin-bottom: 25px;
        }

        .summary p {
            margin: 5px 0;
            font-size: 14px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th {
            background-color: #111827;
            color: white;
            font-size: 13px;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 10px;
            text-align: left;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #6b7280;
        }

    </style>
</head>

<body>

    <h1>
        SmartStock Sales Report
    </h1>

    <div class="summary">

        <p>
            <strong>Total Sales:</strong>
            {{ $totalSales }}
        </p>

        <p>
            <strong>Total Revenue:</strong>
            &#8358;{{ number_format($totalRevenue, 2) }}
        </p>

        <p>
            <strong>Generated At:</strong>
            {{ now()->format('d M Y h:i A') }}
        </p>

    </div>

    <table>

        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Price</th>
            <th>Date</th>
        </tr>

        @foreach($sales as $sale)

        <tr>

            <td>
                {{ $sale->product->name ?? 'Deleted Product' }}
            </td>

            <td>
                {{ $sale->quantity }}
            </td>

            <td>
                &#8358;{{ number_format($sale->total_price, 2) }}
            </td>

            <td>
                {{ $sale->created_at->format('d M Y') }}
            </td>

        </tr>

        @endforeach

    </table>

    <div class="footer">

        Generated by SmartStock Inventory System

    </div>

</body>
</html>